version: "3"

services:
  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    volumes:
      - ./load_test.js:/tests/load_test.js
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"

networks:
  app-network:
    name: app-network
    driver: bridge
